#Copy to codesnifferai/docker-composer.yml
version: '3.2'
services:
    web-app:
        working_dir: /web
        build: .
        volumes:
            - .:/codesnifferai
        ports:
            - "8000:8000"
        expose:
            - "8000"
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 && bin/gunicorn_start