version: '3.2'
services:
    codesnifferai:
        working_dir: /codesnifferai
        build: .
        volumes:
            - .:/codesnifferai
        ports:
            - "8000:8000"
        expose:
            - "8000"
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 && bin/gunicorn_start