# Generated by Django 4.2.4 on 2023-08-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codesnippet",
            options={
                "verbose_name": "CodeSnippet",
                "verbose_name_plural": "CodeSnippet",
            },
        ),
        migrations.RemoveField(
            model_name="codesnippet",
            name="score",
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Scores",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(verbose_name="date created")),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.codesnippet",
                        verbose_name="CodeSnippet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score",
                "verbose_name_plural": "Scores",
            },
        ),
    ]
