# Generated by Django 4.2.4 on 2023-08-30 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_codesnippet_options_remove_codesnippet_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesnippet",
            name="udpated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 30, 16, 3, 42, 645520, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date updated",
            ),
        ),
        migrations.AddField(
            model_name="scores",
            name="udpated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 30, 16, 3, 42, 667884, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date updated",
            ),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 30, 16, 3, 42, 645387, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
        migrations.AlterField(
            model_name="scores",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 30, 16, 3, 42, 667873, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
    ]
