# Generated by Django 4.2.4 on 2023-08-30 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_codesnippet_source_alter_codesnippet_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codesnippet",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="source",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="udpated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="scores",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="scores",
            name="udpated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
