# Generated by Django 4.2.4 on 2023-12-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_codesnippet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='session_key',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
